apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: float-operation
  namespace: openfaas-fn
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: float-operation
  targetCPUUtilizationPercentage: 100
