kind: Profile
apiVersion: openfaas.com/v1
metadata:
  name: function-anti-affinity
  namespace: openfaas
spec:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: faas_function
                operator: In
                values:
                - float-operation
            topologyKey: kubernetes.io/hostname
